[build]
# When 'base' is set, Netlify runs the build inside that subdirectory.
# Therefore the publish path should be relative to that base (just 'dist').
base = "client_react"
publish = "dist"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "20"

# SPA fallback so direct deep links work
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
